"""Core configuration and utilities"""

from .config import Config
from .exceptions import (
    TrouveUnCadeauException,
    ValidationError,
    NotFoundError,
    AirtableServiceError,
    AIServiceError,
    RateLimitError,
    ConfigurationError,
    UnauthorizedError,
    ForbiddenError,
)
from .schemas import (
    ProductBase,
    Product,
    ProductsResponse,
    RecommendationRequest,
    RecommendationItem,
    RecommendationsResponse,
    HealthStatus,
    ServiceHealth,
    ErrorResponse,
    PaginationParams,
    APIInfo,
)
from .middleware import (
    ErrorHandlingMiddleware,
    RequestLoggingMiddleware,
    configure_middleware,
    get_cors_middleware,
)
from .validators import (
    BudgetValidator,
    AgeValidator,
    OccasionValidator,
    InterestValidator,
    RecommendationRequestValidator,
    validate_pagination,
    validate_search_query,
)
from .utils import (
    sanitize_string,
    normalize_text,
    generate_hash,
    format_currency,
    parse_csv_line,
    dict_to_query_string,
    chunk_list,
    get_timestamp,
    safe_get,
    merge_dicts,
    filter_dict,
    log_performance,
    is_valid_email,
    is_valid_url,
)

__all__ = [
    "Config",
    "TrouveUnCadeauException",
    "ValidationError",
    "NotFoundError",
    "AirtableServiceError",
    "AIServiceError",
    "RateLimitError",
    "ConfigurationError",
    "UnauthorizedError",
    "ForbiddenError",
    "ProductBase",
    "Product",
    "ProductsResponse",
    "RecommendationRequest",
    "RecommendationItem",
    "RecommendationsResponse",
    "HealthStatus",
    "ServiceHealth",
    "ErrorResponse",
    "PaginationParams",
    "APIInfo",
    "ErrorHandlingMiddleware",
    "RequestLoggingMiddleware",
    "configure_middleware",
    "get_cors_middleware",
    "BudgetValidator",
    "AgeValidator",
    "OccasionValidator",
    "InterestValidator",
    "RecommendationRequestValidator",
    "validate_pagination",
    "validate_search_query",
    "sanitize_string",
    "normalize_text",
    "generate_hash",
    "format_currency",
    "parse_csv_line",
    "dict_to_query_string",
    "chunk_list",
    "get_timestamp",
    "safe_get",
    "merge_dicts",
    "filter_dict",
    "log_performance",
    "is_valid_email",
    "is_valid_url",
]
